# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interface.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_label = QtWidgets.QVBoxLayout()
        self.verticalLayout_label.setSpacing(6)
        self.verticalLayout_label.setObjectName("verticalLayout_label")
        self.imageLayout = QtWidgets.QHBoxLayout()
        self.imageLayout.setObjectName("imageLayout")
        self.qlabel_image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_image.sizePolicy().hasHeightForWidth())
        self.qlabel_image.setSizePolicy(sizePolicy)
        self.qlabel_image.setStyleSheet("background-color:white\n"
"                                                    ")
        self.qlabel_image.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_image.setLineWidth(1)
        self.qlabel_image.setMidLineWidth(0)
        self.qlabel_image.setText("")
        self.qlabel_image.setObjectName("qlabel_image")
        self.imageLayout.addWidget(self.qlabel_image)
        self.verticalLayout_label.addLayout(self.imageLayout)
        self.verticalLayout_label.setStretch(0, 12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_label)
        self.verticalLayout_filelist = QtWidgets.QVBoxLayout()
        self.verticalLayout_filelist.setSpacing(3)
        self.verticalLayout_filelist.setObjectName("verticalLayout_filelist")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_folder = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.open_folder.setFont(font)
        self.open_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_folder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.open_folder.setAutoFillBackground(False)
        self.open_folder.setStyleSheet(" /*background-color: black; color:white;Blue */padding:10px;                                                      ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icons/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_folder.setIcon(icon)
        self.open_folder.setAutoDefault(False)
        self.open_folder.setDefault(False)
        self.open_folder.setFlat(False)
        self.open_folder.setObjectName("open_folder")
        self.horizontalLayout_2.addWidget(self.open_folder)
        self.open_file = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.open_file.setFont(font)
        self.open_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_file.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.open_file.setAutoFillBackground(False)
        self.open_file.setStyleSheet(" /*background-color: black; color:white;Blue */padding:10px;        ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/icons/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file.setIcon(icon1)
        self.open_file.setAutoDefault(False)
        self.open_file.setDefault(False)
        self.open_file.setFlat(False)
        self.open_file.setObjectName("open_file")
        self.horizontalLayout_2.addWidget(self.open_file)
        self.verticalLayout_filelist.addLayout(self.horizontalLayout_2)
        self.image_list = QtWidgets.QListWidget(self.centralwidget)
        self.image_list.setStyleSheet("background-color:white")
        self.image_list.setFrameShape(QtWidgets.QFrame.Box)
        self.image_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image_list.setLayoutMode(QtWidgets.QListView.Batched)
        self.image_list.setBatchSize(20)
        self.image_list.setObjectName("image_list")
        self.verticalLayout_filelist.addWidget(self.image_list)
        self.phase_tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.phase_tree.setFrameShape(QtWidgets.QFrame.Box)
        self.phase_tree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.phase_tree.setObjectName("phase_tree")
        self.phase_tree.headerItem().setText(0, "phase tree")
        self.verticalLayout_filelist.addWidget(self.phase_tree)
        self.horizontalLayout_4.addLayout(self.verticalLayout_filelist)
        self.verticalLayout_function = QtWidgets.QVBoxLayout()
        self.verticalLayout_function.setSpacing(3)
        self.verticalLayout_function.setObjectName("verticalLayout_function")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_function.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_function)
        self.horizontalLayout_4.setStretch(0, 48)
        self.horizontalLayout_4.setStretch(1, 12)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_open_video = QtWidgets.QMenu(self.menu_file)
        self.menu_open_video.setObjectName("menu_open_video")
        self.menu_open_image = QtWidgets.QMenu(self.menu_file)
        self.menu_open_image.setObjectName("menu_open_image")

        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_workspace = QtWidgets.QMenu(self.menubar)
        self.menu_workspace.setObjectName("menu_workspace")
        self.menu_image = QtWidgets.QMenu(self.menubar)
        self.menu_image.setObjectName("menu_image")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_shortcut = QtWidgets.QAction(MainWindow)
        self.action_shortcut.setObjectName("action_shortcut")
        self.action_man = QtWidgets.QAction(MainWindow)
        self.action_man.setObjectName("action_man")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_toggle_image = QtWidgets.QAction(MainWindow)
        self.action_toggle_image.setObjectName("action_toggle_image")
        self.action_toggle_phase = QtWidgets.QAction(MainWindow)
        self.action_toggle_phase.setObjectName("action_toggle_phase")
        self.action_select_input = QtWidgets.QAction(MainWindow)
        self.action_select_input.setObjectName("action_select_input")
        self.action_clear = QtWidgets.QAction(MainWindow)
        self.action_clear.setObjectName("action_clear")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_open_mulimg = QtWidgets.QAction(MainWindow)
        self.action_open_mulimg.setObjectName("action_open_mulimg")
        self.action_open_video = QtWidgets.QAction(MainWindow)
        self.action_open_video.setObjectName("action_open_video")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_open_dir = QtWidgets.QAction(MainWindow)
        self.action_open_dir.setObjectName("action_open_dir")
        self.menu_open_video.addAction(self.action_open_mulimg)
        self.menu_open_video.addAction(self.action_open_video)
        self.menu_open_image.addAction(self.action_open)
        self.menu_open_image.addAction(self.action_open_dir)
        self.menu_file.addAction(self.menu_open_image.menuAction())
        self.menu_file.addAction(self.menu_open_video.menuAction())
        self.menu_file.addAction(self.action_close)

        self.menu_view.addAction(self.action_toggle_image)
        self.menu_view.addAction(self.action_toggle_phase)
        self.menu_view.addAction(self.action_select_input)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_workspace.menuAction())
        self.menubar.addAction(self.menu_image.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "image process tool"))
        self.open_folder.setToolTip(_translate("MainWindow", "选择一个文件夹，将文件夹中所有的图片文件加载到图片列表 <U>Ctrl+Shift+O</U>"))
        self.open_folder.setText(_translate("MainWindow", "Open Image Fold"))
        self.open_file.setToolTip(_translate("MainWindow", "选择一张图片文件，将其加载到图片列表 <U>Ctrl+O</U>\n"
"                                                            "))
        self.open_file.setText(_translate("MainWindow", "Open Image File"))
        self.image_list.setToolTip(_translate("MainWindow", "打开的图片文件列表"))
        self.phase_tree.setToolTip(_translate("MainWindow", "图片的阶段输出列表"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_open_video.setTitle(_translate("MainWindow", "打开视频"))
        self.menu_open_image.setTitle(_translate("MainWindow", "打开图片"))
        self.menu_view.setTitle(_translate("MainWindow", "查看"))
        self.menu_workspace.setTitle(_translate("MainWindow", "工作空间"))
        self.menu_image.setTitle(_translate("MainWindow", "图像"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_close.setText(_translate("MainWindow", "关闭"))
        self.action_shortcut.setText(_translate("MainWindow", "快捷键表"))
        self.action_man.setText(_translate("MainWindow", "使用手册"))
        self.action_about.setText(_translate("MainWindow", "关于我们"))
        self.action_toggle_image.setText(_translate("MainWindow", "切换图片"))
        self.action_toggle_phase.setText(_translate("MainWindow", "切换阶段输出"))
        self.action_select_input.setText(_translate("MainWindow", "选择输入阶段"))
        self.action_clear.setText(_translate("MainWindow", "清空工作空间"))
        self.action_3.setText(_translate("MainWindow", "打开图片组"))
        self.action_4.setText(_translate("MainWindow", "打开视频文件"))
        self.action_open_mulimg.setText(_translate("MainWindow", "打开图片组"))
        self.action_open_video.setText(_translate("MainWindow", "打开视频文件"))
        self.action_open.setText(_translate("MainWindow", "打开文件"))
        self.action_open_dir.setText(_translate("MainWindow", "打开文件夹"))


