# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_savebatch.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.QVBoxLayout = QtWidgets.QVBoxLayout()
        self.QVBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.QVBoxLayout.setSpacing(12)
        self.QVBoxLayout.setObjectName("QVBoxLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_table = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_table.sizePolicy().hasHeightForWidth())
        self.image_table.setSizePolicy(sizePolicy)
        self.image_table.setFrameShape(QtWidgets.QFrame.Box)
        self.image_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image_table.setObjectName("image_table")
        self.horizontalLayout.addWidget(self.image_table)
        self.cnm = QtWidgets.QVBoxLayout()
        self.cnm.setObjectName("cnm")
        self.phase_table = QtWidgets.QTableView(self.centralwidget)
        self.phase_table.setFrameShape(QtWidgets.QFrame.Box)
        self.phase_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.phase_table.setObjectName("phase_table")
        self.cnm.addWidget(self.phase_table)
        self.horizontalLayout.addLayout(self.cnm)
        self.QVBoxLayout.addLayout(self.horizontalLayout)
        self.shit = QtWidgets.QHBoxLayout()
        self.shit.setObjectName("shit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.shit.addWidget(self.label_3)
        self.fold_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.fold_edit.setReadOnly(True)
        self.fold_edit.setObjectName("fold_edit")
        self.shit.addWidget(self.fold_edit)
        self.fold_button = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icons/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fold_button.setIcon(icon)
        self.fold_button.setObjectName("fold_button")
        self.shit.addWidget(self.fold_button)
        self.QVBoxLayout.addLayout(self.shit)
        self.bitch_2 = QtWidgets.QHBoxLayout()
        self.bitch_2.setObjectName("bitch_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.bitch_2.addWidget(self.label_5)
        self.save_model_combo = QtWidgets.QComboBox(self.centralwidget)
        self.save_model_combo.setObjectName("save_model_combo")
        self.save_model_combo.addItem("")
        self.save_model_combo.addItem("")
        self.bitch_2.addWidget(self.save_model_combo)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.bitch_2.addWidget(self.label_4)
        self.imageFormat_combo = QtWidgets.QComboBox(self.centralwidget)
        self.imageFormat_combo.setObjectName("imageFormat_combo")
        self.imageFormat_combo.addItem("")
        self.imageFormat_combo.addItem("")
        self.imageFormat_combo.addItem("")
        self.imageFormat_combo.addItem("")
        self.imageFormat_combo.addItem("")
        self.bitch_2.addWidget(self.imageFormat_combo)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.bitch_2.addWidget(self.label_6)
        self.tableFormat_combo = QtWidgets.QComboBox(self.centralwidget)
        self.tableFormat_combo.setObjectName("tableFormat_combo")
        self.tableFormat_combo.addItem("")
        self.tableFormat_combo.addItem("")
        self.bitch_2.addWidget(self.tableFormat_combo)
        self.QVBoxLayout.addLayout(self.bitch_2)
        self.bitch = QtWidgets.QHBoxLayout()
        self.bitch.setObjectName("bitch")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.bitch.addWidget(self.label)
        self.info_edit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_edit.sizePolicy().hasHeightForWidth())
        self.info_edit.setSizePolicy(sizePolicy)
        self.info_edit.setMinimumSize(QtCore.QSize(0, 10))
        self.info_edit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.info_edit.setMouseTracking(False)
        self.info_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.info_edit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.info_edit.setReadOnly(True)
        self.info_edit.setObjectName("info_edit")
        self.bitch.addWidget(self.info_edit)
        self.QVBoxLayout.addLayout(self.bitch)
        self.fuck = QtWidgets.QHBoxLayout()
        self.fuck.setObjectName("fuck")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.fuck.addWidget(self.label_2)
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setProperty("value", 12)
        self.progress.setInvertedAppearance(False)
        self.progress.setObjectName("progress")
        self.fuck.addWidget(self.progress)
        self.QVBoxLayout.addLayout(self.fuck)
        self.fuckyou = QtWidgets.QHBoxLayout()
        self.fuckyou.setObjectName("fuckyou")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(0, 50))
        self.start_button.setBaseSize(QtCore.QSize(0, 100))
        self.start_button.setObjectName("start_button")
        self.fuckyou.addWidget(self.start_button)
        self.terminate_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminate_button.sizePolicy().hasHeightForWidth())
        self.terminate_button.setSizePolicy(sizePolicy)
        self.terminate_button.setMinimumSize(QtCore.QSize(0, 50))
        self.terminate_button.setBaseSize(QtCore.QSize(0, 100))
        self.terminate_button.setObjectName("terminate_button")
        self.fuckyou.addWidget(self.terminate_button)
        self.QVBoxLayout.addLayout(self.fuckyou)
        self.gridLayout.addLayout(self.QVBoxLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionopen_dir = QtWidgets.QAction(MainWindow)
        self.actionopen_dir.setObjectName("actionopen_dir")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Batch Save"))
        self.image_table.setToolTip(_translate("MainWindow", "选择列表中需要保存的图片"))
        self.phase_table.setToolTip(_translate("MainWindow", "选择列表中需要保存的阶段输出"))
        self.label_3.setText(_translate("MainWindow", "Save Path :"))
        self.fold_edit.setToolTip(_translate("MainWindow", "保存图片的文件夹路径"))
        self.fold_button.setToolTip(_translate("MainWindow", "选择文件夹"))
        self.fold_button.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "save mode:"))
        self.save_model_combo.setItemText(0, _translate("MainWindow", "save images on single fold"))
        self.save_model_combo.setItemText(1, _translate("MainWindow", "save images on multiple folds"))
        self.label_4.setText(_translate("MainWindow", "save images format:"))
        self.imageFormat_combo.setItemText(0, _translate("MainWindow", "jpg"))
        self.imageFormat_combo.setItemText(1, _translate("MainWindow", "png"))
        self.imageFormat_combo.setItemText(2, _translate("MainWindow", "tif"))
        self.imageFormat_combo.setItemText(3, _translate("MainWindow", "bmp"))
        self.imageFormat_combo.setItemText(4, _translate("MainWindow", "gif"))
        self.label_6.setText(_translate("MainWindow", "save tables format:"))
        self.tableFormat_combo.setItemText(0, _translate("MainWindow", "csv"))
        self.tableFormat_combo.setItemText(1, _translate("MainWindow", "xlsx"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\"> current </span></p><p><span style=\" font-size:8pt;\"> infomation  </span></p></body></html>"))
        self.info_edit.setToolTip(_translate("MainWindow", "当前信息"))
        self.label_2.setText(_translate("MainWindow", "进度 : "))
        self.progress.setFormat(_translate("MainWindow", "%p%"))
        self.start_button.setToolTip(_translate("MainWindow", "开始对选中列表中的图片进行运算，并保存到指定文件夹中"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.terminate_button.setToolTip(_translate("MainWindow", "强制结束进程"))
        self.terminate_button.setText(_translate("MainWindow", "Terminate"))
        self.actionopen.setText(_translate("MainWindow", "打开文件"))
        self.actionopen_dir.setText(_translate("MainWindow", "打开文件夹"))
        self.action.setText(_translate("MainWindow", "关闭"))
        self.action_2.setText(_translate("MainWindow", "快捷键表"))
        self.action_3.setText(_translate("MainWindow", "使用手册"))
        self.action_4.setText(_translate("MainWindow", "关于我们"))


